SET JAVA_HOME=C:\DEV\SDK\JDK\jdk-11.0.9
SET MVN_HOME=C:\DEV\Tools\apache-maven-3.6.3
SET KAFKA_HOME=%TST_BASE_DIR%\kafka_2.13-2.7.0
SET PATH=%JAVA_HOME%\BIN;%MVN_HOME%\BIN;%KAFKA_HOME%\BIN\WINDOWS;%PATH%
